-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-15 23:44:58 BRT
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE SEQUENCE AplicacaoNutrientes_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE Cultura_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE HistoricoClimatico_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE Irrigacao_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE LeituraNutrientes_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE LeituraPH_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE LeituraSensor_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE LeituraUmidade_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE PrevisaoRecomendacao_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE Sensor_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE Talhao_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE SEQUENCE TipoCultura_Seq 
    START WITH 1 
    INCREMENT BY 1 
;

CREATE TABLE AplicacaoNutrientes 
    ( 
     AplicacaoID       NUMBER  NOT NULL , 
     TalhaoID          NUMBER  NOT NULL , 
     DataHora          TIMESTAMP  NOT NULL , 
     TipoNutriente     VARCHAR2 (50) , 
     Quantidade        NUMBER (10,2) , 
     MetodoAplicacao   VARCHAR2 (50) , 
     CondicaoClimatica VARCHAR2 (50) , 
     Formulacao        VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE AplicacaoNutrientes 
    ADD CONSTRAINT AplicacaoNutrientes_PK PRIMARY KEY ( AplicacaoID ) ;

CREATE TABLE Cultura 
    ( 
     CulturaID            NUMBER  NOT NULL , 
     TipoCulturaID        NUMBER  NOT NULL , 
     Variedade            VARCHAR2 (50) , 
     DataPlantio          DATE , 
     DataColheitaPrevista DATE , 
     AreaHectare          NUMBER (10,2) , 
     ProducaoEstimada     NUMBER (10,2) 
    ) 
    LOGGING 
;

ALTER TABLE Cultura 
    ADD CONSTRAINT Cultura_PK PRIMARY KEY ( CulturaID ) ;

CREATE TABLE HistoricoClimatico 
    ( 
     HistoricoID     NUMBER  NOT NULL , 
     TalhaoID        NUMBER  NOT NULL , 
     DataHora        TIMESTAMP  NOT NULL , 
     Temperatura     NUMBER (5,2) , 
     Precipitacao    NUMBER (6,2) , 
     UmidadeAr       NUMBER (5,2) , 
     VelocidadeVento NUMBER (5,2) , 
     DirecaoVento    VARCHAR2 (20) , 
     RadiacaoSolar   NUMBER (6,2) 
    ) 
    LOGGING 
;

ALTER TABLE HistoricoClimatico 
    ADD CONSTRAINT HistoricoClimatico_PK PRIMARY KEY ( HistoricoID ) ;

CREATE TABLE Irrigacao 
    ( 
     IrrigacaoID    NUMBER  NOT NULL , 
     TalhaoID       NUMBER  NOT NULL , 
     DataHora       TIMESTAMP  NOT NULL , 
     QuantidadeAgua NUMBER (10,2) , 
     DuracaoMinutos NUMBER (10) , 
     TipoIrrigacao  VARCHAR2 (30) , 
     PressaoAgua    NUMBER (5,2) , 
     FonteAgua      VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE Irrigacao 
    ADD CONSTRAINT Irrigacao_PK PRIMARY KEY ( IrrigacaoID ) ;

CREATE TABLE LeituraNutrientes 
    ( 
     LeituraNutrientesID NUMBER  NOT NULL , 
     LeituraID           NUMBER  NOT NULL , 
     NivelFosforo        NUMBER (6,2) , 
     NivelPotassio       NUMBER (6,2) , 
     NivelNitrogenio     NUMBER (6,2) , 
     ProfundidadeMedicao NUMBER (5,2) 
    ) 
    LOGGING 
;

ALTER TABLE LeituraNutrientes 
    ADD CONSTRAINT LeituraNutrientes_PK PRIMARY KEY ( LeituraNutrientesID ) ;

CREATE TABLE LeituraPH 
    ( 
     LeituraPHID         NUMBER  NOT NULL , 
     LeituraID           NUMBER  NOT NULL , 
     ValorPH             NUMBER (4,2) , 
     ProfundidadeMedicao NUMBER (5,2) 
    ) 
    LOGGING 
;

ALTER TABLE LeituraPH 
    ADD CONSTRAINT LeituraPH_PK PRIMARY KEY ( LeituraPHID ) ;

CREATE TABLE LeituraSensor 
    ( 
     LeituraID    NUMBER  NOT NULL , 
     SensorID     NUMBER  NOT NULL , 
     TalhaoID     NUMBER  NOT NULL , 
     DataHora     TIMESTAMP  NOT NULL , 
     ValorLeitura NUMBER (10,2) , 
     Unidade      VARCHAR2 (20) 
    ) 
    LOGGING 
;

ALTER TABLE LeituraSensor 
    ADD CONSTRAINT LeituraSensor_PK PRIMARY KEY ( LeituraID ) ;

CREATE TABLE LeituraUmidade 
    ( 
     LeituraUmidadeID    NUMBER  NOT NULL , 
     LeituraID           NUMBER  NOT NULL , 
     PercentualUmidade   NUMBER (5,2) , 
     ProfundidadeMedicao NUMBER (5,2) , 
     TemperaturaAmbiente NUMBER (5,2) 
    ) 
    LOGGING 
;

ALTER TABLE LeituraUmidade 
    ADD CONSTRAINT LeituraUmidade_PK PRIMARY KEY ( LeituraUmidadeID ) ;

CREATE TABLE PrevisaoRecomendacao 
    ( 
     PrevisaoID            NUMBER  NOT NULL , 
     TalhaoID              NUMBER  NOT NULL , 
     DataHoraGeracao       TIMESTAMP  NOT NULL , 
     TipoPrevisao          VARCHAR2 (50) , 
     DescricaoRecomendacao VARCHAR2 (500) , 
     PrioridadeAcao        NUMBER (1) , 
     DataLimiteAcao        DATE , 
     EconomiaEstimada      NUMBER (10,2) 
    ) 
    LOGGING 
;

ALTER TABLE PrevisaoRecomendacao 
    ADD CONSTRAINT PrevisaoRecomendacao_PK PRIMARY KEY ( PrevisaoID ) ;

CREATE TABLE Sensor 
    ( 
     SensorID       NUMBER  NOT NULL , 
     TipoSensor     VARCHAR2 (10)  NOT NULL , 
     Localizacao    VARCHAR2 (100) , 
     DataInstalacao DATE , 
     Status         VARCHAR2 (20) 
    ) 
    LOGGING 
;

ALTER TABLE Sensor 
    ADD CONSTRAINT Sensor_PK PRIMARY KEY ( SensorID ) ;

CREATE TABLE Talhao 
    ( 
     TalhaoID               NUMBER  NOT NULL , 
     CulturaID              NUMBER  NOT NULL , 
     NomeTalhao             VARCHAR2 (50) , 
     AreaHectare            NUMBER (10,2) , 
     DensidadePlantio       NUMBER (10,2) , 
     EspacamentoEntreLinhas NUMBER (5,2) , 
     CicloVegetativo        VARCHAR2 (20) , 
     Latitude               NUMBER (10,6) , 
     Longitude              NUMBER (10,6) , 
     Altitude               NUMBER (6,2) , 
     TipoSolo               VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE Talhao 
    ADD CONSTRAINT Talhao_PK PRIMARY KEY ( TalhaoID ) ;

CREATE TABLE TipoCultura 
    ( 
     TipoCulturaID              NUMBER  NOT NULL , 
     NomeCultura                VARCHAR2 (50)  NOT NULL , 
     DescricaoCultura           VARCHAR2 (200) , 
     TempoMedioCiclo            NUMBER , 
     NecessidadeHidricaMedia    NUMBER (10,2) , 
     NecessidadeNutrientesMedia VARCHAR2 (200) 
    ) 
    LOGGING 
;

ALTER TABLE TipoCultura 
    ADD CONSTRAINT TipoCultura_PK PRIMARY KEY ( TipoCulturaID ) ;

ALTER TABLE AplicacaoNutrientes 
    ADD CONSTRAINT FK_AplicacaoNutrientes_Talhao FOREIGN KEY 
    ( 
     TalhaoID
    ) 
    REFERENCES Talhao 
    ( 
     TalhaoID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Cultura 
    ADD CONSTRAINT FK_Cultura_TipoCultura FOREIGN KEY 
    ( 
     TipoCulturaID
    ) 
    REFERENCES TipoCultura 
    ( 
     TipoCulturaID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE HistoricoClimatico 
    ADD CONSTRAINT FK_HistoricoClimatico_Talhao FOREIGN KEY 
    ( 
     TalhaoID
    ) 
    REFERENCES Talhao 
    ( 
     TalhaoID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Irrigacao 
    ADD CONSTRAINT FK_Irrigacao_Talhao FOREIGN KEY 
    ( 
     TalhaoID
    ) 
    REFERENCES Talhao 
    ( 
     TalhaoID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LeituraNutrientes 
    ADD CONSTRAINT FK_LeituraNutrientes_Leitura FOREIGN KEY 
    ( 
     LeituraID
    ) 
    REFERENCES LeituraSensor 
    ( 
     LeituraID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LeituraPH 
    ADD CONSTRAINT FK_LeituraPH_Leitura FOREIGN KEY 
    ( 
     LeituraID
    ) 
    REFERENCES LeituraSensor 
    ( 
     LeituraID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LeituraSensor 
    ADD CONSTRAINT FK_LeituraSensor_Sensor FOREIGN KEY 
    ( 
     SensorID
    ) 
    REFERENCES Sensor 
    ( 
     SensorID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LeituraSensor 
    ADD CONSTRAINT FK_LeituraSensor_Talhao FOREIGN KEY 
    ( 
     TalhaoID
    ) 
    REFERENCES Talhao 
    ( 
     TalhaoID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LeituraUmidade 
    ADD CONSTRAINT FK_LeituraUmidade_Leitura FOREIGN KEY 
    ( 
     LeituraID
    ) 
    REFERENCES LeituraSensor 
    ( 
     LeituraID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PrevisaoRecomendacao 
    ADD CONSTRAINT FK_PrevisaoRecomendacao_Talhao FOREIGN KEY 
    ( 
     TalhaoID
    ) 
    REFERENCES Talhao 
    ( 
     TalhaoID
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Talhao 
    ADD CONSTRAINT FK_Talhao_Cultura FOREIGN KEY 
    ( 
     CulturaID
    ) 
    REFERENCES Cultura 
    ( 
     CulturaID
    ) 
    NOT DEFERRABLE 
;

CREATE OR REPLACE TRIGGER AplicacaoNutrientes_BI 
    BEFORE INSERT ON AplicacaoNutrientes 
    FOR EACH ROW 
BEGIN
    SELECT AplicacaoNutrientes_Seq.NEXTVAL INTO :NEW.AplicacaoID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER Cultura_BI 
    BEFORE INSERT ON Cultura 
    FOR EACH ROW 
BEGIN
    SELECT Cultura_Seq.NEXTVAL INTO :NEW.CulturaID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER HistoricoClimatico_BI 
    BEFORE INSERT ON HistoricoClimatico 
    FOR EACH ROW 
BEGIN
    SELECT HistoricoClimatico_Seq.NEXTVAL INTO :NEW.HistoricoID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER Irrigacao_BI 
    BEFORE INSERT ON Irrigacao 
    FOR EACH ROW 
BEGIN
    SELECT Irrigacao_Seq.NEXTVAL INTO :NEW.IrrigacaoID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER LeituraNutrientes_BI 
    BEFORE INSERT ON LeituraNutrientes 
    FOR EACH ROW 
BEGIN
    SELECT LeituraNutrientes_Seq.NEXTVAL INTO :NEW.LeituraNutrientesID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER LeituraPH_BI 
    BEFORE INSERT ON LeituraPH 
    FOR EACH ROW 
BEGIN
    SELECT LeituraPH_Seq.NEXTVAL INTO :NEW.LeituraPHID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER LeituraSensor_BI 
    BEFORE INSERT ON LeituraSensor 
    FOR EACH ROW 
BEGIN
    SELECT LeituraSensor_Seq.NEXTVAL INTO :NEW.LeituraID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER LeituraUmidade_BI 
    BEFORE INSERT ON LeituraUmidade 
    FOR EACH ROW 
BEGIN
    SELECT LeituraUmidade_Seq.NEXTVAL INTO :NEW.LeituraUmidadeID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER PrevisaoRecomendacao_BI 
    BEFORE INSERT ON PrevisaoRecomendacao 
    FOR EACH ROW 
BEGIN
    SELECT PrevisaoRecomendacao_Seq.NEXTVAL INTO :NEW.PrevisaoID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER Sensor_BI 
    BEFORE INSERT ON Sensor 
    FOR EACH ROW 
BEGIN
    SELECT Sensor_Seq.NEXTVAL INTO :NEW.SensorID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER Talhao_BI 
    BEFORE INSERT ON Talhao 
    FOR EACH ROW 
BEGIN
    SELECT Talhao_Seq.NEXTVAL INTO :NEW.TalhaoID FROM DUAL;
END; 
/

CREATE OR REPLACE TRIGGER TipoCultura_BI 
    BEFORE INSERT ON TipoCultura 
    FOR EACH ROW 
BEGIN
    SELECT TipoCultura_Seq.NEXTVAL INTO :NEW.TipoCulturaID FROM DUAL;
END; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          12
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         12
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
